import type { Metadata } from 'next';

// These styles apply to every route in the application
import './globals.css';
import PageLayout from '@/components/layout/PageLayout';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

interface RootLayoutProps {
  children: React.ReactNode;
}

const RootLayout = ({ children }: RootLayoutProps) => {
  return (
    <html lang="en">
      <body>
        <div
          style={{
            position: 'fixed',
            left: 0,
            top: 0,
            width: '100%',
            height: '180px',
            backgroundColor: '#ffe000',
          }}
        />
        <PageLayout>{children}</PageLayout>
      </body>
    </html>
  );
};

export default RootLayout;
